name: 'CI Action for Testing'
description: 'Runs tests and generates coverage reports for the testing repository'
runs:
  using: 'composite'  # Use composite to run multiple steps
  steps:
    - name: Run integration and end-to-end tests with coverage
      run: pytest --cov=tests --cov-report=html --cov-report=xml --junitxml=report.xml tests/
      shell: bash

    - name: Run linting
      run: flake8 tests/ --count --show-source --statistics
      shell: bash 