name: Testing CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html

      - name: Run tests with coverage and HTML reports
        run: |
          mkdir -p htmltest
          pytest --cov=tests --cov-report=html --cov-report=xml --html=htmltest/report.html --self-contained-html tests/

      - name: Verify coverage report directory
        run: |
          if [ ! -d "htmlcov" ]; then
            echo "Error: htmlcov/ directory not found. Ensure tests pass and --cov-report=html is enabled."
            exit 1
          fi

      - name: Verify test report directory
        run: |
          if [ ! -d "htmltest" ]; then
            echo "Error: htmltest/ directory not found. Ensure tests pass and --html is enabled."
            exit 1
          fi

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
          compression-level: 0  # Faster upload for HTML files

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: htmltest/
          compression-level: 0  # Faster upload for HTML files
